### ISSUE TITLE
Laravel Internals

### ISSUE THREAD

**Issue by michaelachrisco** [michaelachrisco/ReadOnlyTraitLaravel#12]
References: https://github.com/laravel/internals/issues/396

Should Laravel be leveraging Read Only Events and/or Models within Laravel Core?

**Comment by fernandobandeira** [comment]
I think that probably not since you can actually achieve something like this creating another database connection, you could work with a read/write connection and a read only connection with a db user that has only select privileges.

Then use the read/write connection as the default one and on the models that you need read only behavior you can add:

```php
protected $connection = 'readonly';
```

Of course, if you need all your models to be readonly you may consider creating the default connection with just read privileges.

You can then catch the exception:

```php
Illuminate\Database\QueryException
```

You should be able to get the message from this exception and determine if it was caused by the lack of writing permissions and properly address that.

After considering that you can work like this I don't see any meaning on having this on the core, as it doesn't seem to add anything that you can't already do, maybe I'm missing something? 😄

**Comment by michaelachrisco** [comment]
@fernandobandeira My frame of reference coming into laravel is through trying to find a php framework that is somewhat like Rails. In Rails, I can set a Model to `Model.readonly` or set `@readonly` in the constructor and the model will not save.

I wanted something Laravel can use and not something that needs a database set with a read only user. Whether this functionality should be part of Laravel core is up to you the community, and I appreciate your feedback regarding this issue. In a couple of my projects, this package in addition to a readonly connection to throw an error (or return false).

**Comment by michaelachrisco** [comment]
Closing. If most projects don't need read only models then laravel/internal should not care (YAGNI).
